# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCommitGen < Formula
  desc "AI-powered commit message generator"
  homepage "https://github.com/aryan1306/ai-commit-gen"
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.4/ai-commit-gen_Darwin_x86_64.tar.gz"
      sha256 "8809c8ab17ce516ab22405424a9ee0cef56d39c0e88ea08254b462c70feb00b7"

      def install
        bin.install "ai-commit-gen"
      end
    end
    on_arm do
      url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.4/ai-commit-gen_Darwin_arm64.tar.gz"
      sha256 "7fbf850aee372ddb9143f318e55403d760eeb82c3ce9ac44fc3fb6f5c868fc33"

      def install
        bin.install "ai-commit-gen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.4/ai-commit-gen_Linux_x86_64.tar.gz"
        sha256 "ed71dcaf951f5227a5dc3fbd00b4e25d12e54ac0c6a2fac58cfc919d3a6c0489"

        def install
          bin.install "ai-commit-gen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.4/ai-commit-gen_Linux_arm64.tar.gz"
        sha256 "43fbbd25492458218ab94b67d11fa4a8c6878c193b0b0a64f7548a9ce1560347"

        def install
          bin.install "ai-commit-gen"
        end
      end
    end
  end

  test do
    system "#{bin}/ai-commit-gen --version"
  end
end
