# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCommitGen < Formula
  desc "AI-powered commit message generator"
  homepage "https://github.com/aryan1306/ai-commit-gen"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.5/ai-commit-gen_Darwin_x86_64.tar.gz"
      sha256 "26828c87c6c24656fb2172030c67db13723bd8522cfbe4508f7a350f58844231"

      def install
        bin.install "ai-commit-gen"
      end
    end
    on_arm do
      url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.5/ai-commit-gen_Darwin_arm64.tar.gz"
      sha256 "fdea9d146433623ad93b20ca433c26065bd5688944cd37d8b93b9a4b0752f6cd"

      def install
        bin.install "ai-commit-gen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.5/ai-commit-gen_Linux_x86_64.tar.gz"
        sha256 "d16f5b0f8aaa0a407926b85bbf77bb868c1a70ca40dbb3b6024617863fb07e01"

        def install
          bin.install "ai-commit-gen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.5/ai-commit-gen_Linux_arm64.tar.gz"
        sha256 "c270d2d82f5f1a3642238481d7e27315740015e451144afbe89f88c809b51beb"

        def install
          bin.install "ai-commit-gen"
        end
      end
    end
  end

  test do
    system "#{bin}/ai-commit-gen --version"
  end
end
