# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCommitGen < Formula
  desc "AI-powered commit message generator"
  homepage "https://github.com/aryan1306/ai-commit-gen"
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.6/ai-commit-gen_Darwin_x86_64.tar.gz"
      sha256 "eccefd4acabe73cdf0259eb9ba4207cb63e45646a543be63e1b0ce75b4fafbac"

      def install
        bin.install "ai-commit-gen"
      end
    end
    on_arm do
      url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.6/ai-commit-gen_Darwin_arm64.tar.gz"
      sha256 "b73c52e8ff40793197c1b32ce8a4a9e5253e10b3e2dd41e6dbe5895d25062890"

      def install
        bin.install "ai-commit-gen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.6/ai-commit-gen_Linux_x86_64.tar.gz"
        sha256 "51cc5e3330ee96daa9d29473f6607e8e5d587736bebc4b528f016afae9b5cf3d"

        def install
          bin.install "ai-commit-gen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aryan1306/ai-commit-gen/releases/download/v0.1.6/ai-commit-gen_Linux_arm64.tar.gz"
        sha256 "2ed1eac48126848579fee8b84b9c5322d768ecc7484e7b94f5805c7e125a93ba"

        def install
          bin.install "ai-commit-gen"
        end
      end
    end
  end

  test do
    system "#{bin}/ai-commit-gen --version"
  end
end
